#!/usr/bin/env bash

# Buildbot master directory
master="$HOME/buildbot/master"

# Default branch of `git-ci` repo to use
branch="master"

export PATH="$HOME/.local/bin:$PATH"

bb_checkconfig() {
    buildbot checkconfig "$master"
}

bb_reconfig() {
    bb_checkconfig \
        && buildbot reconfig "$master"
}

bb_restart() {
    bb_checkconfig \
        && buildbot restart "$master"
}

bb_worker() {
    local worker_command worker_name worker_password worker_port

    worker_command="$1" ; shift
    worker_name="$1"    ; shift

    case "$worker_command" in
        create) worker_password="$1" ; shift
                worker_port="$1"     ; shift
                buildbot-worker create-worker "$HOME/buildbot/$worker_name" localhost:"$worker_port" "$worker_name" "$worker_password"
                ;;
        *)      buildbot-worker "$worker_command" "$HOME/buildbot/$worker_name"
                ;;
    esac
}

bb_command="$1" && shift
case "$bb_command" in
    checkconfig) bb_checkconfig      ;;
    reconfig)    bb_reconfig         ;;
    restart)     bb_restart          ;;
    worker)      bb_worker      "$@" ;;
    *) echo "
usage: $0 [checkconfig|reconfig|restart]
       $0 worker [start|stop|restart] [worker-name]
"
       exit 1
       ;;
esac
