#!/usr/bin/env bash

export GIT_WORK_TREE="$HOME/src/git-ci"
export GIT_DIR="$GIT_WORK_TREE/.git"
export PATH="$HOME/.local/bin:$PATH"

branch="master"
[[ -z "$1" ]] || branch="$1"

git fetch && git reset --hard "origin/$branch"
